### ISSUE TITLE
module tests

### ISSUE THREAD

**Issue by parro-it** [brrd/electron-is-accelerator#1]
Hi, I will add some tests to `electron-is-accelerator`;
 I'm thinking to use it to validate [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) input, but I would prefer to have some test on `electron-is-accelerator` first.

Are you ok if I use AVA for the tests?

**Comment by brrd** [comment]
Sure! (I don't know AVA but it looks great)
Thanks!
